CHARACTER_SPEAKING_STYLES = {
    "Saki": "Female high-school student. Energetic, direct, hyper-competitive, hates losing. Sometimes uses third-person pronouns.",
    "Temari": "Female high-school student. Cool, stoic, sarcastic, and sharp-tongued on the surface; underneath she can be clingy, fragile, lazy, and awkwardly dependent.",
    "Kotone": "Female high-school student. Cheerful, cute, informal, approval-seeking, and money-conscious. Can sound sweet or calculating depending on context.",
    "Mao": "Female high-school student. Dorm head and caring upperclassman. Uses a princely, gentle 'Boku' voice; aims for coolness but is also nurturing and elegant.",
    "Lilja": "Female high-school student. Shy, self-effacing, nervous, and earnest. Speaks humbly, with quiet determination when it matters.",
    "China": "Female high-school student. Sheltered ojou-sama type: innocent, graceful, polite, and enthusiastic. Use refined 'desu wa'-like elegance rather than simply 'large vocabulary'.",
    "Sumika": "Female high-school student. Bright, friendly, unserious gyaru. Use casual trendy slang lightly; a Valley-girl flavor can work in informal English, but avoid over-caricaturing her.",
    "Hiro": "Female high-school student. Mysterious genius. Calm, odd, blunt, and fascinated by hardship or failure; can sound detached or quietly delighted by strange things.",
    "Rinami": "Female high-school student. Mature, gentle onee-san archetype. Caring, composed, domestic, and softly teasing or attentive.",
    "Ume": "Female high-school student. Loud, energetic, athletic younger-sister type who adores Saki. Slightly airheaded and straightforward. Can use Gen Alpha slang if the text is deliberately slangy.",
    "Sena": "Female high-school student. Student council president and elite idol. Proud, confident, dignified, and charismatic; speaks like someone used to being admired.",
    "Tsubame": "Female high-school student. Student council vice president. Proud, strict, direct, severe, and intimidating, but responsible and caring underneath. Formal/commanding diction; do not overuse archaic Japanese unless the source line does.",
    "Rinha": "Female high-school student, rival-school character. Cool, strict, sharp, and duty/contract-minded; can be harsh, but has a loyal and caring core. Lower-confidence: verify against in-game lines.",
    "Misuzu": "Female high-school student. Calm, laid-back, sleepy, gentle, and indulgent. Speaks softly and at her own pace.",
    "Shion": "Female high-school student, rival/antagonist. Polite and composed on the surface, but cold, malicious, strategic, and cutting. When emotional, may break into rougher, more aggressive speech.",
    "Gekka": "Female high-school student, rival/antagonist. Top-class, cold, terse, dismissive, and authoritative. Speaks with intimidating economy rather than flowery verbosity.",
    "Nadeshiko": "Female high-school student, rival/antagonist. Spoiled ojou-sama/brat type: high-handed, self-confident, dramatic, and 'desu wa' coded. More comic-small-villain than truly composed.",
    "Asari-sensei": "Female teacher. Friendly, kind homeroom-teacher voice. Mature, supportive, and approachable rather than stern.",
    "{user}": "Male producer character. Treat as a Producer Department student: young-adult/student tone, relaxed but respectful.",
}
