CHARACTER_SPEAKING_STYLES = {
    "Saki": "Female, High Schooler, Speaks energetically, and might sometimes refers to herself in third person",
    "Temari": "Female, High Schooler, Speaks with a harsh tone that usually came out of being socially awkward, but has a gentle and shy side",
    "Kotone": "Female, High Schooler, Speak with a cheerful and slightly informal tone",
    "Mao": "Female, High Schooler, Dorm head of the idol school, caring",
    "Lilja": "Female, High Schooler, Speaks shyly",
    "China": "Female, High Schooler, Speaks with a wide range of vocabulary while still sounding innocent and graceful",
    "Sumika": "Female, High Schooler, Speaks with gyaru slangs, use valley girl accents in english when she's speaking informally",
    "Hiro": "Female, High Schooler, A genius girl who gives off a mysterious vibe",
    "Rinami": "Female, High Schooler, Speaks like an older sister(Onee-san archetype)",
    "Ume": "Female, High Schooler, Speaks loudly, and like a younger sister, might also incorporate gen alpha slangs, a little bit airheaded",
    "Sena": "Female, High Schooler, Speaks proudly and with confidence",
    "Tsubame": "Female, High Schooler, Speaks in a harsh and direct tone that might scare younger girls, can use old Japanese.",
    "Rinha": "Female, High Schooler, Speaks in a cool manner",
    "Misuzu": "Female, High Schooler, Speaks in calm and laid back manner",
    "Shion": "Female, High Schooler, Antagonist, wide range of vocabulary",
    "Gekka": "Female, High Schooler, Antagonist, wide range of vocabulary",
    "Nadeshiko": "Female, High Schooler, Antagonist, Speaks like a spoiled brat",
    "Asari-sensei": "Female, Speaks like a mature teacher",
    "{user}": "Male, the Producer character, Speaks like a college student",
}
